name: Docker Image CI for GHCR

on:
  push:

jobs:
  build_and_public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username pathone --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/pathone/arithmetic-service:latest --file Dockerfile .
          docker push ghcr.io/pathone/arithmetic-service:latest
  